
package m1.archi.hotel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HotelServiceConsultationImplService", targetNamespace = "http://service.archi.m1/", wsdlLocation = "http://localhost:8080/hotelservice/H1699887523990/consultation?wsdl")
public class HotelServiceConsultationImplService
    extends Service
{

    private final static URL HOTELSERVICECONSULTATIONIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HOTELSERVICECONSULTATIONIMPLSERVICE_EXCEPTION;
    private final static QName HOTELSERVICECONSULTATIONIMPLSERVICE_QNAME = new QName("http://service.archi.m1/", "HotelServiceConsultationImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/hotelservice/H1699887523990/consultation?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOTELSERVICECONSULTATIONIMPLSERVICE_WSDL_LOCATION = url;
        HOTELSERVICECONSULTATIONIMPLSERVICE_EXCEPTION = e;
    }

    public HotelServiceConsultationImplService() {
        super(__getWsdlLocation(), HOTELSERVICECONSULTATIONIMPLSERVICE_QNAME);
    }

    public HotelServiceConsultationImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOTELSERVICECONSULTATIONIMPLSERVICE_QNAME, features);
    }

    public HotelServiceConsultationImplService(URL wsdlLocation) {
        super(wsdlLocation, HOTELSERVICECONSULTATIONIMPLSERVICE_QNAME);
    }

    public HotelServiceConsultationImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOTELSERVICECONSULTATIONIMPLSERVICE_QNAME, features);
    }

    public HotelServiceConsultationImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelServiceConsultationImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HotelServiceConsultation
     */
    @WebEndpoint(name = "HotelServiceConsultationImplPort")
    public HotelServiceConsultation getHotelServiceConsultationImplPort() {
        return super.getPort(new QName("http://service.archi.m1/", "HotelServiceConsultationImplPort"), HotelServiceConsultation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelServiceConsultation
     */
    @WebEndpoint(name = "HotelServiceConsultationImplPort")
    public HotelServiceConsultation getHotelServiceConsultationImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.archi.m1/", "HotelServiceConsultationImplPort"), HotelServiceConsultation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOTELSERVICECONSULTATIONIMPLSERVICE_EXCEPTION!= null) {
            throw HOTELSERVICECONSULTATIONIMPLSERVICE_EXCEPTION;
        }
        return HOTELSERVICECONSULTATIONIMPLSERVICE_WSDL_LOCATION;
    }

}
