
package m1.archi.hotel;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelServiceConsultation", targetNamespace = "http://service.archi.m1/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HotelServiceConsultation {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns java.util.List<m1.archi.hotel.Offre>
     * @throws DateNonValideException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getChambreDisponibleCriteres", targetNamespace = "http://service.archi.m1/", className = "m1.archi.hotel.GetChambreDisponibleCriteres")
    @ResponseWrapper(localName = "getChambreDisponibleCriteresResponse", targetNamespace = "http://service.archi.m1/", className = "m1.archi.hotel.GetChambreDisponibleCriteresResponse")
    @Action(input = "http://service.archi.m1/HotelServiceConsultation/getChambreDisponibleCriteresRequest", output = "http://service.archi.m1/HotelServiceConsultation/getChambreDisponibleCriteresResponse", fault = {
        @FaultAction(className = DateNonValideException_Exception.class, value = "http://service.archi.m1/HotelServiceConsultation/getChambreDisponibleCriteres/Fault/DateNonValideException")
    })
    public List<Offre> getChambreDisponibleCriteres(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6)
        throws DateNonValideException_Exception
    ;

}
