
package m1.archi.hotel;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "HotelAlreadyExistsException", targetNamespace = "http://service.archi.m1/")
public class HotelAlreadyExistsException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private HotelAlreadyExistsException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public HotelAlreadyExistsException_Exception(String message, HotelAlreadyExistsException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public HotelAlreadyExistsException_Exception(String message, HotelAlreadyExistsException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: m1.archi.hotel.HotelAlreadyExistsException
     */
    public HotelAlreadyExistsException getFaultInfo() {
        return faultInfo;
    }

}
