
package m1.archi.hotel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HotelServiceIdentificationImplService", targetNamespace = "http://service.archi.m1/", wsdlLocation = "http://localhost:8080/hotelservice/identifiantHotels?wsdl")
public class HotelServiceIdentificationImplService
    extends Service
{

    private final static URL HOTELSERVICEIDENTIFICATIONIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HOTELSERVICEIDENTIFICATIONIMPLSERVICE_EXCEPTION;
    private final static QName HOTELSERVICEIDENTIFICATIONIMPLSERVICE_QNAME = new QName("http://service.archi.m1/", "HotelServiceIdentificationImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/hotelservice/identifiantHotels?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOTELSERVICEIDENTIFICATIONIMPLSERVICE_WSDL_LOCATION = url;
        HOTELSERVICEIDENTIFICATIONIMPLSERVICE_EXCEPTION = e;
    }

    public HotelServiceIdentificationImplService() {
        super(__getWsdlLocation(), HOTELSERVICEIDENTIFICATIONIMPLSERVICE_QNAME);
    }

    public HotelServiceIdentificationImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOTELSERVICEIDENTIFICATIONIMPLSERVICE_QNAME, features);
    }

    public HotelServiceIdentificationImplService(URL wsdlLocation) {
        super(wsdlLocation, HOTELSERVICEIDENTIFICATIONIMPLSERVICE_QNAME);
    }

    public HotelServiceIdentificationImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOTELSERVICEIDENTIFICATIONIMPLSERVICE_QNAME, features);
    }

    public HotelServiceIdentificationImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelServiceIdentificationImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HotelServiceIdentification
     */
    @WebEndpoint(name = "HotelServiceIdentificationImplPort")
    public HotelServiceIdentification getHotelServiceIdentificationImplPort() {
        return super.getPort(new QName("http://service.archi.m1/", "HotelServiceIdentificationImplPort"), HotelServiceIdentification.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelServiceIdentification
     */
    @WebEndpoint(name = "HotelServiceIdentificationImplPort")
    public HotelServiceIdentification getHotelServiceIdentificationImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.archi.m1/", "HotelServiceIdentificationImplPort"), HotelServiceIdentification.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOTELSERVICEIDENTIFICATIONIMPLSERVICE_EXCEPTION!= null) {
            throw HOTELSERVICEIDENTIFICATIONIMPLSERVICE_EXCEPTION;
        }
        return HOTELSERVICEIDENTIFICATIONIMPLSERVICE_WSDL_LOCATION;
    }

}
