
package m1.archi.hotel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelServiceReservation", targetNamespace = "http://service.archi.m1/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HotelServiceReservation {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @return
     *     returns m1.archi.hotel.Reservation
     * @throws DateNonValideException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reserverChambres", targetNamespace = "http://service.archi.m1/", className = "m1.archi.hotel.ReserverChambres")
    @ResponseWrapper(localName = "reserverChambresResponse", targetNamespace = "http://service.archi.m1/", className = "m1.archi.hotel.ReserverChambresResponse")
    @Action(input = "http://service.archi.m1/HotelServiceReservation/reserverChambresRequest", output = "http://service.archi.m1/HotelServiceReservation/reserverChambresResponse", fault = {
        @FaultAction(className = DateNonValideException_Exception.class, value = "http://service.archi.m1/HotelServiceReservation/reserverChambres/Fault/DateNonValideException")
    })
    public Reservation reserverChambres(
        @WebParam(name = "arg0", targetNamespace = "")
        Offre arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9)
        throws DateNonValideException_Exception
    ;

}
