
package m1.archi.agence;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AgenceServiceIdentificationImplService", targetNamespace = "http://service.archi.m1/", wsdlLocation = "http://localhost:8090/agencesservice/identifiantAgences?wsdl")
public class AgenceServiceIdentificationImplService
    extends Service
{

    private final static URL AGENCESERVICEIDENTIFICATIONIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException AGENCESERVICEIDENTIFICATIONIMPLSERVICE_EXCEPTION;
    private final static QName AGENCESERVICEIDENTIFICATIONIMPLSERVICE_QNAME = new QName("http://service.archi.m1/", "AgenceServiceIdentificationImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/agencesservice/identifiantAgences?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGENCESERVICEIDENTIFICATIONIMPLSERVICE_WSDL_LOCATION = url;
        AGENCESERVICEIDENTIFICATIONIMPLSERVICE_EXCEPTION = e;
    }

    public AgenceServiceIdentificationImplService() {
        super(__getWsdlLocation(), AGENCESERVICEIDENTIFICATIONIMPLSERVICE_QNAME);
    }

    public AgenceServiceIdentificationImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGENCESERVICEIDENTIFICATIONIMPLSERVICE_QNAME, features);
    }

    public AgenceServiceIdentificationImplService(URL wsdlLocation) {
        super(wsdlLocation, AGENCESERVICEIDENTIFICATIONIMPLSERVICE_QNAME);
    }

    public AgenceServiceIdentificationImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGENCESERVICEIDENTIFICATIONIMPLSERVICE_QNAME, features);
    }

    public AgenceServiceIdentificationImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgenceServiceIdentificationImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AgenceServiceIdentification
     */
    @WebEndpoint(name = "AgenceServiceIdentificationImplPort")
    public AgenceServiceIdentification getAgenceServiceIdentificationImplPort() {
        return super.getPort(new QName("http://service.archi.m1/", "AgenceServiceIdentificationImplPort"), AgenceServiceIdentification.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AgenceServiceIdentification
     */
    @WebEndpoint(name = "AgenceServiceIdentificationImplPort")
    public AgenceServiceIdentification getAgenceServiceIdentificationImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.archi.m1/", "AgenceServiceIdentificationImplPort"), AgenceServiceIdentification.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGENCESERVICEIDENTIFICATIONIMPLSERVICE_EXCEPTION!= null) {
            throw AGENCESERVICEIDENTIFICATIONIMPLSERVICE_EXCEPTION;
        }
        return AGENCESERVICEIDENTIFICATIONIMPLSERVICE_WSDL_LOCATION;
    }

}
