
package m1.archi.agence;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ReservationProblemeException", targetNamespace = "http://service.archi.m1/")
public class ReservationProblemeException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ReservationProblemeException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ReservationProblemeException_Exception(String message, ReservationProblemeException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ReservationProblemeException_Exception(String message, ReservationProblemeException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: m1.archi.agence.ReservationProblemeException
     */
    public ReservationProblemeException getFaultInfo() {
        return faultInfo;
    }

}
